### ISSUE TITLE
Hovering over a button that's on cooldown removes the timer from it

### ISSUE THREAD

**Issue by johnsolver** [tullamods/tullaCC#11] opened 2016-10-28 04:11 UTC
Not sure if this is still 'supported' but since 7.1 if you hover over a button that's on CD the timer gets removed.

**Comment by Tuller** [comment] 2016-10-28 13:19
Will try and reproduce. tullaCC/range should be updated by the end of the
week, I just happened to be very busy this time around.

**Comment by Tuller** [comment] 2016-10-28 23:00
This should be fixed with the latest release.

**Comment by johnsolver** [comment] 2016-10-29 03:05
Yes it is, and so is the shadow on charges, thanks.

However it seems that something is still causing the timer to disappear sometimes (? not sure how, but it does in combat) I assume it's related to 'enable == 1' in the condition since after removing it, it works consistently.

**Comment by Tuller** [comment] 2016-10-29 21:33
Removing the enable check was indeed the fix.  Turns out, it isn't passed for everything.

**Closed** 2017-04-30 13:54 UTC
Labels: bug
